version: "1.0"

services:
  app:
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "8000:80"

  local-redis:
      image: redis:7.2
      restart: always
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql